# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yaro's space for programming
description: Reflections on the art of programming # write a nice description for your blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://yarospace.github.io' # the subpath of your site, e.g. /blog
# google_analytics: 'UA-XXXXXX-X'
# twitter_username: 'twitter_username'

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ['highlight']

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
